### ISSUE TITLE
[Feature Request] Adding "Devices" button

### ISSUE THREAD

**Issue by mmahmoudian** [bilelmoussaoui/revoke.app#12]
Some websites have a part for "trusted devices". Their difference from sessions can be:
1. The session can expire and asks for username and password, but the trusted devices are about 2FA.
2. The website has trusted devices (e.g Apple) that sends 2FA to

For example:
- In a new commit to this repo, the contributor had [linked to devices rather than sessions](https://github.com/bilelmoussaoui/revoke.app/pull/11/commits/130af9adba40d09c27f72dcf23432073eac77859) and the reason is Apple settings does not have any place for sessions (as they do not matter) but has a section for devices
- Lastpass ([Link to the help page](https://support.logmeininc.com/lastpass/help/manage-account-settings-lp010017#Trusted)
- Microsoft ([Link to the settings for devices](https://account.microsoft.com/devices/))
- Google ([Link to the settings for devices](https://myaccount.google.com/device-activity))

We then can use the same button for SSH keys (they are also to some extent device-specific) for websites like Github or Gitlab.

**Comment by bilelmoussaoui** [comment]
I think we can have multiple type of buttons, one for the trusted devices and another one for keys :) it shouldn't be a complex change, just add a new condition here https://github.com/bilelmoussaoui/revoke.app/blob/master/layouts/index.html#L67-L73 and if the new variable is defined on a TOML file, it will be displayed

**Comment by mmahmoudian** [comment]
I created a [PR for for it](https://github.com/bilelmoussaoui/revoke.app/pull/13)

**Comment by bilelmoussaoui** [comment]
This can be closed now I guess?

**Comment by bilelmoussaoui** [comment]
the new button broke the UI a bit :/

**Comment by mmahmoudian** [comment]
> the new button broke the UI a bit :/

You are right, the only solutions come to my mind are:
1. increasing the width of the boxes (this will also help in having the "Researchgate" name in one line as well
2. add a second row to the buttons

I vote for the first, would that be ok?

**Comment by mmahmoudian** [comment]
well, scratch that. I realized you have used screen percentage and for different displays a different number of items in each row. My new proposal:

```css
.button{
    padding-left:.7em;
    padding-right:.7em;
}
```

it would be like:
![image](https://user-images.githubusercontent.com/390889/83243760-055fdb80-a1a7-11ea-9e47-66f0f6dbd66e.png)

**Comment by bilelmoussaoui** [comment]
It looks good, but what if we end up adding a new button for something else tomorrow? :P I think breaking to a new line makes more sense but not sure how that would look like.

I also plan to make the website translatable in the future so Apps/Sessions/Devices might take a larger width than it's the case currently with English

**Comment by mmahmoudian** [comment]
> I also plan to make the website translatable in the future

so then the RTL languages would also be a nice thing to consider ;)

**Comment by bilelmoussaoui** [comment]
> > I also plan to make the website translatable in the future
> 
> so then the RTL languages would also be a nice thing to consider ;)

I'm a native Arabic speaker, it will be considered for sure

**Comment by mmahmoudian** [comment]
I think this issue has served the purpose. for the UI fix, perhaps another issue should be created for more easier-to-follow thread. Thanks for the discussion.

**Comment by bilelmoussaoui** [comment]
Thanks I have fixed it by using smaller buttons :)
